with open('docs/multi-agent-extension-report.html', 'r', encoding='utf-8') as f:
    html = f.read()

pres = html.count('<pre')
svgs = html.count('<svg class="diagram"')
tables = html.count('<table')
cap_grids = html.count('class="cap-grid"')
api_lists = html.count('class="api-list"')
scenarios = html.count('class="scenario-timeline"')
flow_steps = html.count('class="flow-steps"')
comp_grids = html.count('class="comparison-grid"')
tree_cards = html.count('class="tree-card"')

print(f'Remaining <pre> tags: {pres}')
print(f'SVG diagrams: {svgs}')
print(f'<table> tags: {tables}')
print(f'')
print(f'Visual components inserted:')
print(f'  cap-grid: {cap_grids}')
print(f'  api-list: {api_lists}')
print(f'  scenario-timeline: {scenarios}')
print(f'  flow-steps: {flow_steps}')
print(f'  comparison-grid: {comp_grids}')
print(f'  tree-card: {tree_cards}')
